//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageSchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        public Agent()
        {
            this.ProductSale = new HashSet<ProductSale>();
        }
    
        public int Id { get; set; }
        public string TypeAgent { get; set; }
        public string NameAgent { get; set; }
        public string EmailAgent { get; set; }
        public string PhoneAgent { get; set; }
        public string PhotoPath { get; set; }
        public string Address { get; set; }
        public Nullable<int> Priotity { get; set; }
        public string Director { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual ICollection<ProductSale> ProductSale { get; set; }
    }
}
