//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageSchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductSale = new HashSet<ProductSale>();
        }
    
        public int Id { get; set; }
        public string NameProduct { get; set; }
        public string TypeProduct { get; set; }
        public string ProductArticleNumber { get; set; }
        public Nullable<int> CountPeopleForMade { get; set; }
        public Nullable<int> WorkShopNumber { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual ICollection<ProductSale> ProductSale { get; set; }
    }
}
